 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
    registerWithEureka: true
    fetchRegistry: true
    
 app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000